version: '3.7'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379"
  app:
    image: devops_test:latest
    build:
      context: .
    environment:
      - REDIS_ADDR=redis:6379
    ports:
        - "8080:8080"
        - "9000:9000"
    depends_on:
       - redis

  redis-exporter:
      image: oliver006/redis_exporter
      ports:
        - 9121:9121
      environment:
        - REDIS_ADDR=redis:6379

networks:
  default:
    external:
      name: cross-network
