apiVersion: v1
kind: Service
metadata:
  name: devops-test-go-metrics-expose-service
spec:
  selector:
    app: App
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000
  type: LoadBalancer
